### PR TITLE
added prune distance to pruneGlobalPlan if robot passed via_point

### PR DESCRIPTION
**Pull request by mgruhler**
exposes prune_distance as a ROS parameter.

Please let me know if the allocated position in the structs does not suit you.

### CODE REVIEW

**Comment by croesmann** [comment]
thanks for the PR! Unfortunately, there are some conflicts due to some other merged changes. Could you resolve those issues (shouldn't be a big deal)? And mabye, we should rename `prune_distance` to `global_plan_prune_distance` to comply with the other global plan related parameters.

Let me know if you are busy to update PR

**Comment by mgruhler** [comment]
@croesmann, thanks for the feedback.

I'll update the PR as requested, but will only be able to do so in the week after next, as I don't have a ROS machine with me atm.
So I won't feel hurt if you resolve this yourself ;-) But it is not that urgent for me, so feel free to choose what is more suitable for you.

**Comment by croesmann** [comment]
ok, I did this minor change in the last commit by myself to include this in the next release that I am going to push today. Thanks!
Note, I have not included this parameter in dynamic reconfigure in order to keep the number of parameters low ;-). However, we could add this someday when the parameter is subject to be changed frequently.

**Comment by mgruhler** [comment]
Cool. Thx so much! Appreciate your work here :+1:

**Pull request closed without merging**
