### PR TITLE
Dashing devel

### PR DESCRIPTION
**Pull request by vinnamkim**
This PR is porting TEB local planner to ROS2(Dashing-Diademata). It is compatible with Navigation2 stack. You can test it by launching the following command.
```
ros2 launch teb_local_planner teb_simulation_launch.py
```

Related to https://github.com/rst-tu-dortmund/teb_local_planner/issues/154

### CODE REVIEW

**Comment by vinnamkim** [comment]
This PR can be build-able after merging [this PR of Navigation2](https://github.com/ros-planning/navigation2/pull/981)

**Comment by vinnamkim** [comment]
@mkhansen-intel Right, I guess @croesmann would give me the new branch to merge.

**Comment by croesmann** [comment]
many thanks for your work!! I haven't reviewed and tested yet, but just one question that comes to my mind: do we actually need the dependency on dwb_local_planner (dwb_* packages)?

Btw, I changed the target branch to dashing-devel.

**Comment by vinnamkim** [comment]
@mkhansen-intel 
I'm fine to attend the meeting. However, I'm worried that it would be meaningless to attend since I'm extremely not good at English.

**Comment by vinnamkim** [comment]
@croesmann 

Since there are two dependencies on dwb_local_planner (dwb_* packages) to port it to ROS2.

[1. Checking trajectory feasibility](https://github.com/rst-tu-dortmund/teb_local_planner/blob/89602b29979163f12bec71d17304887cde296bad/teb_local_planner/src/optimal_planner.cpp#L1220)
I was originally depend on `base_local_planner::CostmapModel`. But same functionalities are ported to `dwb_critics::ObstacleFootprintCritic` in nav2, and I decided to use them.

[2. Progress checker](https://github.com/rst-tu-dortmund/teb_local_planner/blob/89602b29979163f12bec71d17304887cde296bad/teb_local_planner/src/teb_controller.cpp#L60)
It was not included in your original code. I guess there is same code to check how the robot is close to goal in your [original code](https://github.com/rst-tu-dortmund/teb_local_planner/blob/260c0ef06d02035d44acff58dceb934b002c7b41/src/teb_local_planner_ros.cpp#L264). But, I decided to put it in like [nav2's `DwbController`](https://github.com/ros-planning/navigation2/blob/d7e8b65e7b31ced76738c01bd16f3fc84f886527/nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp#L72). I just wanted to make [TebController](https://github.com/rst-tu-dortmund/teb_local_planner/blob/89602b29979163f12bec71d17304887cde296bad/teb_local_planner/include/teb_local_planner/teb_controller.hpp#L36) to share almost of the codes with `DwbController`, in case that nav2 will have common interfaces for local planners.

**Comment by croesmann** [comment]
I just checked your code @vinnamkim. Awesome, thanks a lot for porting the code to ros2. I don't have a ros2 test setup yet. However, I am going to create one soon for extensive testing.
But I am still fine with merging the current state to dashing-devel. We can address further changes by new PRs :-)

**Pull request merged**
