### PR TITLE
[ros2-mater] Sync with melodic-devel 

### PR DESCRIPTION
**Pull request by doisyg**
As discussed here: https://github.com/rst-tu-dortmund/teb_local_planner/issues/283

One main point to discuss before merging: goal reach checking. There was some melodic code that was not ported : 
https://github.com/rst-tu-dortmund/teb_local_planner/blob/0d242c0aff4f81b4ff5d67d7e4f970a8f454ad4a/src/teb_local_planner_ros.cpp#L287-L301
In the current ros2 branch there is this code marked for goal reach checking : 
https://github.com/rst-tu-dortmund/teb_local_planner/blob/e3acd7d0d7519406cd136a6d8fead0f783025363/teb_local_planner/src/teb_local_planner_ros.cpp#L299-L302
But I don't get how it is done.

More generally, maybe we should remove the code related to goal checking since in nav2 it is done by a controller pluggin, @SteveMacenski, what do you think ?

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@doisyg I changed the base of your PR to ros2, I assume that's what you meant :-)

**Review by SteveMacenski — APPROVED** [review]
From a high level, seems reasonable. At this junction, would testing be wise? Or after this goes in?

**Comment by SteveMacenski** [comment]
>  But I don't get how it is done.

I don't think it is done. `global_goal` is never used to compare against. That looks like a block of dead code

**Comment by doisyg** [comment]
> @doisyg I changed the base of your PR to ros2, I assume that's what you meant :-)

Yes, thanks!

**Comment by doisyg** [comment]
> > But I don't get how it is done.
> 
> I don't think it is done. `global_goal` is never used to compare against. That looks like a block of dead code

Agreed, I added a commit which removes the parameters which were used in this goal reach check and which are not used anywhere in the ROS2 code : `trans_stopped_vel`, `theta_stopped_vel`, `yaw_goal_tolerance` and `complete_global_plan`. I believe they are functionaly replaced in ROS2 by the goal checker (hence my recent PR https://github.com/ros-planning/navigation2/pull/2248)
There is still `xy_goal_tolerance` which is used here:
https://github.com/rst-tu-dortmund/teb_local_planner/blob/e3acd7d0d7519406cd136a6d8fead0f783025363/teb_local_planner/src/graph_search.cpp#L102
and here:
https://github.com/rst-tu-dortmund/teb_local_planner/blob/e3acd7d0d7519406cd136a6d8fead0f783025363/teb_local_planner/src/graph_search.cpp#L233
and that we should, I believe, get from the `goal_checker` param (and if possible, dynamically), but this will be the task of another PR

**Comment by SteveMacenski** [comment]
>  and that we should, I believe, get from the goal_checker param (and if possible, dynamically), but this will be the task of another PR

Indeed, if fact this wouldn't build with Nav2 without adding that `goal_checker` arg after https://github.com/ros-planning/navigation2/pull/2247 is merged. You'll have access to it immediately after that to remove that last param

**Comment by SteveMacenski** [comment]
Merge this? What about testing?

**Comment by doisyg** [comment]
> > and that we should, I believe, get from the goal_checker param (and if possible, dynamically), but this will be the task of another PR
> 
> Indeed, if fact this wouldn't build with Nav2 without adding that `goal_checker` arg after [ros-planning/navigation2#2247](https://github.com/ros-planning/navigation2/pull/2247) is merged. You'll have access to it immediately after that to remove that last param

Ok, I will keep an eye on this

**Comment by doisyg** [comment]
> Merge this? What about testing?

Yes please, building against last nav2 main. Basic test with a real robot done.
Still planning to do extensive testing of each feature once everything is merged. I updated the plan here: https://github.com/rst-tu-dortmund/teb_local_planner/issues/283 (end of first post)

**Pull request merged**
