### PR TITLE
[ros2-mater] Sync with noetic-devel 

### PR DESCRIPTION
**Pull request by doisyg**
As discussed here: https://github.com/rst-tu-dortmund/teb_local_planner/issues/283
Include the PR fixing compilation: https://github.com/rst-tu-dortmund/teb_local_planner/pull/281
First part of the maintenance plan for ros2-master.
Compiles and runs fine, no extensive checks done yet.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
I just very _very_ briefly skimmed over it to make sure everything looked sane, but is there any thing else you'd like us to do before merging this backported content into ROS2-master? 

We should probably do some minimal sanity checking that it fixed some of the issues that those PRs aimed to solve

**Comment by doisyg** [comment]
> I just very _very_ briefly skimmed over it to make sure everything looked sane, but is there any thing else you'd like us to do before merging this backported content into ROS2-master?

Not at the moment, melodic sync will follow once this is merged.

> We should probably do some minimal sanity checking that it fixed some of the issues that those PRs aimed to solve

I agree, I am planning to check the behavior of each one of the commit/PR and report in the table there: https://github.com/rst-tu-dortmund/teb_local_planner/issues/283 . But I will do it once most of the sync/merge are done. I am under the impression (from my colleagues report), that some PR were buggy or introduced some bugs already in ROS1.

**Comment by SteveMacenski** [comment]
> But I will do it once most of the sync/merge are done. I am under the impression (from my colleagues report), that some PR were buggy or introduced some bugs already in ROS1.

Wait, so you think there are bugs this PR might be introducing from these PRs? Wouldn't we want to test them then _before_ merging them if we feel there's a high chance of introducing issues?

**Comment by doisyg** [comment]
No on this PR (to the best of my knowledge), but I am expecting to have to correct few things and the fly when porting the melodic sync.

**Pull request merged**
