### PR TITLE
Humble maintenance

### PR DESCRIPTION
**Pull request by doisyg**
Sharing here our last galactic and humble changes to TEB:

- adaptation to libg2o api changes, similar to https://github.com/rst-tu-dortmund/teb_local_planner/commit
/d5fc3fea6e9b77664b53dfefa0261aa9a6635190 but without creating the extra `register_type` function (hence the merge conflict)
- same dynamic parameter method as nav2
- dynamic footprint parameter (but with the limitation that the footprint type cannot change at runtime), @guilyx
- get base and global frames from costmap (and hence remove unnecessary `map_frame` param)
- Humble adaptations: tf2_geometry_msgs.h depreciation, nav2 PR 2976 changes (https://github.com/ros-planning/navigation2/pull/2976),  compiler warnings and fix costmap_converter plugin load

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
Generally speaking, I'd just take your word for it. I haven't been following this repo much and I don't have the cycles to add it to my regular maintenance schedule.

**Comment by doisyg** [comment]
Great, I ll perform some additional checks and confirm this PR next week once I will have access to a real robot.

**Comment by doisyg** [comment]
Confirming than this has been extensively tested on a real robot (with a circular footprint) and that some basic sim test have been done with a polygon footprint.

**Comment by SteveMacenski** [comment]
Git claims there's a conflict that needs to be resolved before I can merge

**Comment by doisyg** [comment]
Solved

**Pull request merged**
