### PR TITLE
control_look_ahead_poses can now be dynamically reconfigured

### PR DESCRIPTION
**Pull request by siferati**

### CODE REVIEW

**Comment by corot** [comment]
We have noticed that this parameter is very useful for robots a bit lethargic reacting to commands. Setting to a higher than 1 value reduces progressively oscillations around the global path. However, 1 is the perfect value for precise control of the same lethargic robots when moving slow.

**Comment by AlperenKosem** [comment]
for instance :
[https://github.com/rst-tu-dortmund/teb_local_planner/issues/10](url)

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@corot I'm not an admin on here on the ROS 1 side, but for something trivial like this I can merge it, but that shouldn't be the baseline expectation.

**Comment by corot** [comment]
> @corot I'm not an admin on here on the ROS 1 side, but for something trivial like this I can merge it, but that shouldn't be the baseline expectation.

Got it. I volunteered myself to help maintaining for ROS1, so if you can provide some reviews, it will be more than enough.
It's of if I keep tagging you for future reviews? Thanks!

**Comment by SteveMacenski** [comment]
I cannot provide reviews for ROS 1, I have too many other responsibilities, I cannot add this among them

**Pull request merged**
